name: sr_rom
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - numpy
  - pytorch
  - cpuonly
  - joblib
  - scikit-learn
  - pytest
  - pytest-cov
  - pip:  
    - skorch
    - pyoperon
    
